<h1><?php echo $this->titulo?></h1>
 


<?php $nombre ="nombre_prueba";

	foreach($datos as $dato){
	?>
	
		<?php if ($nombre != $dato["nombre_trabajador"]) {?>
			<br>
			<br>
			<b>-Nombre: </b><?php echo $dato["nombre_trabajador"]?> <b>Apellidos: </b> <?php echo $dato["apellido_trabajador"]?> <b>Puesto: </b><?php echo $dato["puesto_trabajador"]?>
			<b>Proyectos en los que ha participado: </b>
		<?php }?>
				
			<?php echo $dato["nombre_proyecto"]?> <?php if ($dato["estado_proyecto"]==0) {
				echo "(cerrado),";
			}else{
				echo "(abierto)," ;
				}?>
		
		<?php $nombre = $dato["nombre_trabajador"]?>
		
	<?php }?>

